---
title: "Creating Arrays with NumPy"
author: "Puneet Thukral"
date: 2021-02-11T06:00:00
slug: "creating_arrays"
draft: false
---

## Resources
+ [NumPy](https://numpy.org/doc/stable/user/whatisnumpy.html)
+ [NumPy API](https://numpy.org/doc/stable/reference/index.html)

In [1]:
# Import NumPy
import numpy as np

In [2]:
# Create a list
list_1 = [1,2,3,4,5]
# Create another list # we will use this later
list_2 = [6,7,8,9,10]

## Create an Array with a List

In [3]:
# Create a array by passing the list as an object
new_array = np.array(list_1)
new_array

array([1, 2, 3, 4, 5])

## Create a multi-dimensional array or matrix 

In [4]:
# Create a list of lists
list_of_lists = [list_1, list_2]
list_of_lists

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
# Create a multi-dimensional array or matrix 
matrix_array = np.array(list_of_lists)
matrix_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Check Array Data Type, Dimension or Shape

In [6]:
# Check Array Data Type # Can be Mixed
matrix_array.dtype

dtype('int32')

In [7]:
# Check Number of Dimensions
matrix_array.ndim

2

In [8]:
# Check Array Shape
matrix_array.shape

(2, 5)

## Creating Arrays with Ones or Zeros
### These are built-in functions for creating arrays from scratch

In [9]:
## Create Zeros Array
np.zeros(3)

array([0., 0., 0.])

In [10]:
## Create Zeros Array with Shape
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
## Create Ones Array
np.ones(3)

array([1., 1., 1.])

In [12]:
## Create Ones Array with Shape
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Creating Arrays with Arrange Examples


In [13]:
#Creating Arrays with Arrange
#numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
np.arange(3)

array([0, 1, 2])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

In [15]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [16]:
np.arange(3,33,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])